### ISSUE TITLE
Setting of environment variables in Instrumenting IIS is broken

### ISSUE THREAD

**Issue by danielodievich** [open-telemetry/opentelemetry-dotnet-instrumentation#1593] opened 2022-11-08 19:00 UTC
# Bug Report

## Symptom

On Windows Server 2019 running IIS, `Register-OpenTelemetryForIIS` cmdlet in OpenTelemetry.DotNet.Auto.psm1 fails to set Environment variables for the W3SVC and WAS with this error:

```
Set-ItemProperty: RegistryKey.SetValue does not support arrays of type 'Object[]'. Only Byte[] and String[] are supported.
```

**Expected behavior**
Necessary environment variables are set

**Versions of Software**
- OpenTelemetry Automatic Instrumentation version: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.4.0-beta.1
- OS:
OS Name	Microsoft Windows Server 2019 Standard
Version	10.0.17763 Build 17763
- .NET version: 
.NET 4.7

**Additional context**
Trying to experiment with instrumenting of Dynamics CRM 365 version 9.1

## Reproduce

I modified the script to dump the variables and -Verbose to the Set-ItemProperty:

```powershell
function Setup-Windows-Service([string]$InstallDir, [string]$WindowsServiceName, [string]$OTelServiceName) {  
    $varsTable = Get-Environment-Variables-Table -InstallDir $InstallDir -OTelServiceName $OTelServiceName
    $varsList = ($varsTable.Keys | foreach-object { "$_=$($varsTable[$_])" })
    $varsList
    $regPath = "HKLM:SYSTEM\CurrentControlSet\Services\"
    $regKey = Join-Path $regPath $WindowsServiceName
   
    if (Test-Path $regKey) {
        Set-ItemProperty $regKey -Name Environment -Value $varsList -Verbose
    }
    else {
        throw "Invalid service '$WindowsServiceName'. Service does not exist."
    }
}
```

And I see this:

```powershell
PS C:\otel> Import-Module .\OpenTelemetry.DotNet.Auto.psm1
PS C:\otel> Register-OpenTelemetryForIIS
DOTNET_STARTUP_HOOKS=c:\otel\bin\netcoreapp3.1\OpenTelemetry.AutoInstrumentation.StartupHook.dll
DOTNET_ADDITIONAL_DEPS=c:\otel\bin\AdditionalDeps
COR_PROFILER_PATH_64=c:\otel\bin\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
DOTNET_SHARED_STORE=c:\otel\bin\store
COR_ENABLE_PROFILING=1
CORECLR_PROFILER_PATH_32=c:\otel\bin\win-x86\OpenTelemetry.AutoInstrumentation.Native.dll
COR_PROFILER_PATH_32=c:\otel\bin\win-x86\OpenTelemetry.AutoInstrumentation.Native.dll
COR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER_PATH_64=c:\otel\bin\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
CORECLR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
OTEL_DOTNET_AUTO_HOME=c:\otel\bin\
OTEL_DOTNET_AUTO_INTEGRATIONS_FILE=c:\otel\bin\integrations.json
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrappe

VERBOSE: Performing the operation "Set Property" on target "Item: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC Property: Environment".
VERBOSE: Performing the operation "Set Property" on target "Item: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WAS Property: Environment".

Attempting stop...
Internet services successfully stopped
Attempting start...
Internet services successfully restarted

Set-ItemProperty: RegistryKey.SetValue does not support arrays of type 'Object[]'. Only Byte[] and String[] are supported.
Set-ItemProperty: RegistryKey.SetValue does not support arrays of type 'Object[]'. Only Byte[] and String[] are supported.
```

## Possible Solution

I modified `Setup-Windows-Service` function in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/OpenTelemetry.DotNet.Auto.psm1#L118, specifying the type of the inbound properties to be MultiString:

```powershell
        Set-ItemProperty $regKey -Name Environment -Value $varsList -Type MultiString -Verbose
```

This successfully sets the `Environment` property:

```powershell
PS C:\Windows\System32> Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC

DependOnService     : {WAS, HTTP}
Description         : @%windir%\system32\inetsrv\iisres.dll,-30004
DisplayName         : @%windir%\system32\inetsrv\iisres.dll,-30003
ErrorControl        : 1
ImagePath           : C:\Windows\system32\svchost.exe -k iissvcs
ObjectName          : localSystem
RequiredPrivileges  : {SeAssignPrimaryTokenPrivilege, SeAuditPrivilege, SeBackupPrivilege, SeChangeNotifyPrivilege…}
ServiceSidType      : 0
Start               : 2
SvcHostSplitDisable : 1
Type                : 32
FailureActions      : {255, 255, 255, 255…}
Environment         : {DOTNET_STARTUP_HOOKS=c:\otel\bin\netcoreapp3.1\OpenTelemetry.AutoInstrumentation.StartupHook.dll
                      , COR_PROFILER_PATH_64=c:\otel\bin\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll,
                      CORECLR_ENABLE_PROFILING=1,
                      CORECLR_PROFILER_PATH_64=c:\otel\bin\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll…}
PSPath              : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC
PSParentPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
PSChildName         : W3SVC
PSDrive             : HKLM
PSProvider          : Microsoft.PowerShell.Core\Registry
```

I reran the script:
```powershell
PS C:\Windows\System32> cd C:\otel
PS C:\otel> Import-Module .\OpenTelemetry.DotNet.Auto.psm1
PS C:\otel> Register-OpenTelemetryForIIS
VERBOSE: Performing the operation "Set Property" on target "Item: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC Property: Environment".
VERBOSE: Performing the operation "Set Property" on target "Item: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WAS Property: Environment".

Attempting stop...
Internet services successfully stopped
Attempting start...
Internet services successfully restarted
```

IIS started and I can see the environment variables applied:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/11668602/200651437-b65f679e-1916-462e-bbaa-26a9ccc4bf1c.png">

I can see OTEL assemblies:
![image](https://user-images.githubusercontent.com/11668602/200651869-7caa3cb6-e97e-4e64-81d0-a812d7fd01b8.png)

I can see logging showing we're in in the "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\otel-dotnet-auto-native-w3wp-10100.log":
```
[2022-11-08T18:39:59.862341000Z] [10100|8544] [info] OpenTelemetry CLR Profiler 0.4.0 on Windows (amd64)
[2022-11-08T18:39:59.864481800Z] [10100|8544] [info] CallTarget instrumentation is enabled.
[2022-11-08T18:39:59.864528600Z] [10100|8544] [info] JIT Inlining is enabled.
[2022-11-08T18:39:59.864546100Z] [10100|8544] [info] NGEN is disabled.
[2022-11-08T18:39:59.864589100Z] [10100|8544] [info] Profiler attached.
[2022-11-08T18:39:59.928350200Z] [10100|8544] [info] COR library: mscorlib 4.0.0
[2022-11-08T18:40:01.562476700Z] [10100|8544] [info] JITCompilationStarted: Startup hook registered in function_id=140714580057416 token=100688374 name=System.Web.Compilation.BuildManager.InvokePreStartInitMethods(), assembly_name=System.Web app_domain_id=140716185075616 domain_neutral=1
[2022-11-08T18:40:01.586917200Z] [10100|8544] [info] ModuleLoadFinished: OpenTelemetry.AutoInstrumentation.Loader loaded into AppDomain 2211619426080 [/LM/W3SVC/1/ROOT-1-133124064002993226]
[2022-11-08T18:40:01.628879700Z] [10100|8544] [info] AssemblyLoadFinished: OpenTelemetry.AutoInstrumentation was not loaded domain-neutral
[2022-11-08T18:47:40.946411600Z] [10100|8544] [info] ModuleLoadFinished: OpenTelemetry.AutoInstrumentation.Loader loaded into AppDomain 2211195016192 [/LM/W3SVC/1/ROOT/Help-2-133124068609154467]
[2022-11-08T18:47:40.962181500Z] [10100|8544] [info] AssemblyLoadFinished: OpenTelemetry.AutoInstrumentation was not loaded domain-neutral
```

**Comment by pjanotti** [comment] 2022-11-08 19:03
Thanks for the detailed report @danielodievich!

@RassK could you please take care of this one?

**Comment by pjanotti** [comment] 2022-11-08 20:05
Perhaps folks already know why this was not captured by CI, but, I expected this type of error to be surfaced by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3422483185/jobs/5699945366#step:3:1

Anything that can be done to ensure that the test catches this type of issue?

**Comment by RassK** [comment] 2022-11-08 20:56
@pjanotti seems duplicate of https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1510

Just wondering that it surfaced now on WS2019. I'm running multiple WS2019 VMs and none had this issue, soon after WS2016 was setup, it was present. 
Our GH runners are even WS2022 based.

**Comment by danielodievich** [comment] 2022-11-08 21:02
All this was done in PowerShell 7.
I've tested the steps on Windows 10 machine with PowerShell 7, and on Windows 2019 with classic PowerShell 5, all with same results.

**Comment by RassK** [comment] 2022-11-08 21:16
@danielodievich Thanks for these details! 
I think the fix made in #1510 should cover all these cases now. 

You can grab the latest PS module from the main branch. Let me know, if it still doesn't work out.

**Comment by danielodievich** [comment] 2022-11-09 17:37
I was able to test the latest fix. It appears to register quite nicely.

However, note that it clobbers the existing `Environment` overrides if they already exist. 

I set up these separate out of the setup script and these disappear:
```
OTEL_TRACES_EXPORTER="otlp"
OTEL_METRICS_EXPORTER="otlp"
```

**Comment by RassK** [comment] 2022-11-09 22:00
Yes, currently the setup script wins in every case. It's quite a lot simplified currently.

There are multiple scopes to choose as a main.
1. Respect existing IIS service environments (might be wrong or outdated, in some case even conflicting)
2. Respect session variables set before running `Register-OpenTelemetryForIIS` (Might also conflict with existing globals if session one is missing)
3. Respect global variables set before running `Register-OpenTelemetryForIIS`

CC: @pellared

**Comment by pellared** [comment] 2022-11-10 14:32
If possible I suggest to:

1. During registration- respect existing (do not override) env vars but add the missing ones
2. During unregistration - remove all "related env vars" (make sure to not remove additional env vars)

**Comment by danielodievich** [comment] 2022-11-10 20:58
In my testing, "2. During unregistration - remove all "related env vars" (make sure to not remove additional env vars)" is already how it works.

**Comment by Kielek** [comment] 2023-01-25 15:03
Milestone removed to reveal on SIG meeting.
We should decide if 
During registration - respect existing (do not override) env vars but add the missing ones
or
During registration - set all env. vars. to be sure that setup is correct - not further changes needed (recommended by @RassK).

**Comment by pellared** [comment] 2023-01-25 15:11
I agree with @RassK recommendation, because as far as I see the env vars are coupled to the installed auto-instrumntation version. Some values may change in future and then we want to override them.

**Comment by pjanotti** [comment] 2023-01-25 17:23
SIG: let's go with @RassK recommendation.

**Closed by pjanotti** 2023-01-25 17:23 UTC
