### ISSUE TITLE
No SqlClient traces generated in .NET Framework Web Services Application

### ISSUE THREAD

**Issue by Kronos11** [open-telemetry/opentelemetry-dotnet-instrumentation#2177] opened 2023-02-09 00:28 UTC
# Bug Report

## Symptom

**Describe the bug**
In a .NET Framework Web Services application I am not seeing any traces generated.
When setting up a web.config to 
```
<appSettings>
    <add key="OTEL_SERVICE_NAME" value="TEST_WEB_APP"/>
    <add key="OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED" value="true"/>
  </appSettings>
```
and attaching debugger to application pool and executing anything on a Microsoft.Data.SqlClient or System.Data.SqlClient I see the following error
`ERROR: Exception in Command Processing for EventSource Microsoft-AdoNet-SystemData: Use of undefined keyword value 0x1 for event BeginExecute.`

I mainly see this happen on SqlCommand.ExecuteReader, but I still get no sql traces from any other commands.

**Expected behavior**
SqlClient traces to be sent to OTLP collector

**Screenshots**
In Visual Studio:
```
The thread 0x9014 has exited with code 0 (0x0).
ERROR: Exception in Command Processing for EventSource Microsoft-AdoNet-SystemData: Use of undefined keyword value 0x1 for event BeginExecute.
The program '[27012] w3wp.exe: Program Trace' has exited with code 0 (0x0).
The program '[27012] w3wp.exe' has exited with code 0 (0x0).
```

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: 0.6.0-beta1
- OS: Windows 11 Enterprise 21H2
- .NET version:. NET Framework [4.6.2, 4.7.2, 4.8.0]

**Additional context**

## Reproduce

 1. Download latest (0.6.0-beta1) Powershell module 
 2. run powershell commands
```
Import-Module "./OpenTelemetry.DotNet.Auto.psm1"
Install-OpenTelemetryCore
Register-OpenTelemetryForIIS
```

 5. Download repro application here: https://github.com/Kronos11/OTelWebApplicationTest
 6. Setup local SQLServer with simple demo db and table
 7. run application and debug attaching process
 8. See the error mentioned above

[otel-dotnet-auto-loader-_LM_W3SVC_1_ROOT_WebApplicationTest-15-133203754481900105-16-27012.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/10691204/otel-dotnet-auto-loader-_LM_W3SVC_1_ROOT_WebApplicationTest-15-133203754481900105-16-27012.log)

**Comment by pellared** [comment] 2023-02-09 10:02
Looks like this is caused by https://github.com/open-telemetry/opentelemetry-dotnet/issues/3901

We even have a skipped test for it here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/test/IntegrationTests/SqlClientSystemDataTests.cs

Unfortunately, I do not think it can be nicely solved until Microsoft publishes a fix.
Right now should set `OTEL_DOTNET_AUTO_TRACES_SQLCLIENT_INSTRUMENTATION_ENABLED=false`

PS. `OTEL_DOTNET_AUTO_DEBUG` has to be set as env var. See [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.6.0-beta.1/docs/config.md#configuration-methods)

CC @ajcvickers

**Comment by Kronos11** [comment] 2023-02-09 16:15
I understand it being broken on 4.8.1, but it's also broken all the way down to version 4.6.2 ?
I guess I don't quite understand that?

**Comment by itoledo** [comment] 2023-02-09 16:23
It's broken on 4.6.2 on Windows 11, I used an HyperV VM to test with Windows Server 2019 and everything works fine there. Same code.

**Comment by Kronos11** [comment] 2023-02-09 16:30
> 

This is great to know. I was also going to test it on our Windows Servers.

**Comment by pjanotti** [comment] 2023-02-09 21:39
LIkely reason for failing in Windows 11 and working on Windows Server: https://github.com/open-telemetry/opentelemetry-dotnet/issues/3901#issuecomment-1424518007

**Comment by Kronos11** [comment] 2023-02-09 22:30
I totally forgot this was how .NET Framework worked since I've been mostly doing .NET Core in the last few years.
I think I will be OK for my use case since we will not be going past Windows Server 2019 for now

**Comment by zacharycmontoya** [comment] 2023-02-15 17:20
Closing, we will track this issue via https://github.com/open-telemetry/opentelemetry-dotnet/issues/3901

**Closed by zacharycmontoya** 2023-02-15 17:20 UTC
