### ISSUE TITLE
Microsoft.Extensions.* still cause issues with older version of .NET in v1.5.0

### ISSUE THREAD

**Issue by BenB196** [open-telemetry/opentelemetry-dotnet-instrumentation#3370] opened 2024-04-12 15:35 UTC
# Bug Report

## Symptom

**Describe the bug**

When using any version of this library > 1.1.0, .NET applications < .NET 8 can crash.

**Expected behavior**

When using any version of this library > 1.1.0, .NET applications < .NET 8 don't crash.

**Screenshots**

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: >1.1.0 (tested up to 1.5.0)
- OS: Linux
- .NET version: .NET 6 & .NET 7 ASP

**Additional context**

Observed crashes:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

2024-04-12T15:30:46.505318855Z File name: 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c.<ConfigureDefaults>b__11_2(HostBuilderContext hostingContext, ILoggingBuilder logging)
2024-04-12T15:30:46.505325907Z    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_1.<ConfigureLogging>b__1(ILoggingBuilder builder)
2024-04-12T15:30:46.505328090Z    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureLogging>b__0(HostBuilderContext context, IServiceCollection collection)
2024-04-12T15:30:46.505333925Z    at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
2024-04-12T15:30:46.505336584Z    at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
2024-04-12T15:30:46.505340441Z    at Program.<Main>$(String[] args) in /src/<snipped>/src/<snipped>/Program.cs:line 14
   at Program.<Main>(String[] args)
```

```
Unhandled exception. System.Security.VerificationException: Method Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton: type argument 'Microsoft.Extensions.Logging.ConsoleLoggerFormatterConfigureOptions`2[TFormatter,TOptions]' violates the constraint of type parameter 'TImplementation'.
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsoleFormatter[TFormatter,TOptions](ILoggingBuilder builder)
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggingBuilder builder)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass16_0.<AddDefaultServices>b__0(ILoggingBuilder logging)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.AddDefaultServices(HostBuilderContext hostingContext, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/<snipped>/Program.cs:line 10
   at Program.<Main>(String[] args)
```

## Reproduce

 1. First step;
 2. Second step;
 3. etc

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>

**Comment by rajkumar-rangaraj** [comment] 2024-04-12 15:41
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

This issue was fixed in 1.5.0 version of auto-instrumentation. Could you please provide a demo application that could recreate this issue.

**Comment by BenB196** [comment] 2024-04-12 15:53
Hi @rajkumar-rangaraj that's actually why I just opened this, I just tried with 1.5.0 and am still observing the issue.

![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/8277432/726a687c-5c92-419b-a1a9-7ef202c2bfe4)

**Comment by rajkumar-rangaraj** [comment] 2024-04-12 16:35
If you could provide the list of packages used in the app, that would be helpful.

**Comment by BenB196** [comment] 2024-04-12 17:23
Hi @rajkumar-rangaraj here is the list of deps;

```
<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="MediatR" Version="12.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
<PackageReference Include="MongoDB.Bson" Version="2.22.0" />
<PackageReference Include="MongoDB.Driver" Version="2.22.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
<PackageReference Include="MongoDB.Driver" Version="2.22.0" />
<PackageReference Include="DotNetCore.CAP" Version="7.2.1" />
<PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="7.2.1" />
<PackageReference Include="DotNetCore.CAP.Kafka" Version="7.2.1" />
<PackageReference Include="DotNetCore.CAP.OpenTelemetry" Version="7.2.1" />
<PackageReference Include="FluentValidation" Version="11.7.1" />
<PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1" />
<PackageReference Include="MediatR" Version="12.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.22" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.11" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
<PackageReference Include="OpenTelemetry" Version="1.6.0" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.6.0" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
<PackageReference Include="Polly" Version="7.2.4" />
<PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
<PackageReference Include="Scrutor" Version="4.2.2" />
<PackageReference Include="Serilog" Version="3.0.1" />
<PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
<PackageReference Include="Serilog.Settings.Configuration" Version="7.0.1" />
<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />

```

**Comment by rajkumar-rangaraj** [comment] 2024-04-17 00:26
I could not recreate the exception with these packages - `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

Would it be possible to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that recreate this issue.

**Comment by BenB196** [comment] 2024-04-17 11:23
I'll see if I can put something together in the next few days.

**Comment by pjanotti** [comment] 2024-05-01 16:07
SIG: @BenB196 we are not able to investigate without a repro, @rajkumar-rangaraj tried but no luck. Please, re-open if needed.

**Closed by pjanotti** 2024-05-01 16:07 UTC

**Comment by 116davinder** [comment] 2025-01-16 06:21
I am seeing the same issue on dotnet 7 with otel 1.9.0 for dotnet.

```txt
Unhandled exception. System.Security.VerificationException: Method Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton: type argument 'Microsoft.Extensions.Logging.ConsoleLoggerFormatterConfigureOptions`2[TFormatter,TOptions]' violates the constraint of type parameter 'TImplementation'.
```

**Comment by Kielek** [comment] 2025-01-16 06:34
@116davinder, .NET 6 and .NET7 are EOL.
I doubt that we will be able to help with this. For sure, we need exact steps to reproduce as mentioned earlier.

**Comment by PStyron209** [comment] 2025-04-18 15:17
Hi,
I came across this issue today. Happy to open a new ticket if that's preferable.

I can reproduce this issue consistently using the Microsoft .NET 8 sample app eShopOnWeb. Once built, the architecture sets up three Docker Containers. You can add OTEL to the Dockerfile of one of them and reproduce the problem. Steps to reproduce:

1. SSH to a Linux VM and install Docker Compose
2. Clone the eShopOnWeb repo: git clone https://github.com/dotnet-architecture/eShopOnWeb.git
3. Open the Dockerfile for one of the Containers to add OTEL: vi eShopOnWeb/src/Web/Dockerfile

`#### Before
20 FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
 21 WORKDIR /app
 22 COPY --from=build /app/src/Web/out ./
23
24 # Optional: Set this here if not setting it from docker-compose.yml
25 # ENV ASPNETCORE_ENVIRONMENT Development
26
27 ENTRYPOINT ["dotnet", "Web.dll"]

#### After
21 FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
22 WORKDIR /app
23 COPY --from=build /app/src/Web/out ./
24
25 # Optional: Set this here if not setting it from docker-compose.yml
26 # ENV ASPNETCORE_ENVIRONMENT Development
27
28 RUN apt -y update && apt -y upgrade
29 RUN apt install -y curl unzip
30
31 ADD https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/otel-dotnet-auto-install.sh .
32 RUN sh ./otel-dotnet-auto-install.sh && \
33     chmod +x /root/.otel-dotnet-auto/instrument.sh
34
35 CMD ["/bin/bash", "-c", ". /root/.otel-dotnet-auto/instrument.sh;dotnet Web.dll"]
`

4. Build the App: docker-compose build
5. Run the App: docker-compose up
6. Container eshopwebmvc_1 will not come up and the Console Logging throws error:

`eshopwebmvc_1     | Unhandled exception. System.Security.VerificationException: Method Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton: type argument 'Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2[Microsoft.Extensions.Logging.Console.ConsoleLoggerOptions,Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider]' violates the constraint of type parameter 'TImplementation'.
eshopwebmvc_1     |    at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggingBuilder builder)
eshopwebmvc_1     |    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass16_0.<AddDefaultServices>b__0(ILoggingBuilder logging)
eshopwebmvc_1     |    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
eshopwebmvc_1     |    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.AddDefaultServices(HostBuilderContext hostingContext, IServiceCollection services)
eshopwebmvc_1     |    at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
eshopwebmvc_1     |    at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
eshopwebmvc_1     |    at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
eshopwebmvc_1     |    at Program.<Main>$(String[] args) in /app/src/Web/Program.cs:line 22
eshopwebmvc_1     |    at Program.<Main>(String[] args)
sqlserver_1       | 2025/04/18 15:12:41 [launchpadd] WARNING: Failed to connect to SQL because: dial tcp [::1]:1431: getsockopt: connection refused, will reattempt connection.
eshoponweb_eshopwebmvc_1 exited with code 139`
