### ISSUE TITLE
[Feature Request] Replace the exception during the instrumentation loading with the warning

### ISSUE THREAD

**Issue by yzhoholiev** [open-telemetry/opentelemetry-dotnet-instrumentation#875] opened 2022-06-23 08:42 UTC
# Feature Request

Replace the exception during the instrumentation loading with the logging of the warning.

**Is your feature request related to a problem? Please describe.**

Replace the exception during the instrumentation loading with the logging of the warning, to not break the entire startup of the instrumentation and improve a backward compatibility in case of centralized management of the configuration (when the new instrumentation is added, but older versions of the auto instrumentation are still in use).

**Describe the solution you'd like**

Consider replacing the throwing of the `FormatException` during the configuration loading
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0a539f9f6636b14c0f8006dfce6d58a55e4f53f0/src/OpenTelemetry.AutoInstrumentation/Configuration/MeterSettings.cs#L45-L52

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0a539f9f6636b14c0f8006dfce6d58a55e4f53f0/src/OpenTelemetry.AutoInstrumentation/Configuration/TracerSettings.cs#L46-L53

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pellared** [comment] 2022-06-23 09:43
Our current approach is described here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#error-handling

The reason is that the user may notice the misconfiguration when it is too late (e.g. when the application is having problems). We prefer to fail fast. It is in line with https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md 

You can also read more here when we were deciding to choose this behavior: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/231 

> improve a backward compatibility in case of centralized management of the configuration (when the new instrumentation is added, but older versions of the auto instrumentation are still in use)

This is not backward compatibility as you would add new instrumentation 😉

However, we are working on enabling all instrumentations by default in a such way that the auto instrumentations are applied in a "non-breaking" way. This should make users happier. See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/388

We also cannot safely change the `throw` to logging error as they may be side-effects caused by improper instrumentation loading (e.g. some assemblies may be loaded).

**Comment by pellared** [comment] 2022-06-30 08:59
I think the only potentially undesired behavior would be if we remove some instrumentation library, but I would rather prefer that we "fail" and notify the user that we stopped instrumenting some library rather than just rely on the changelog and release notes.

@yzhoholiev Let me know if you accept such a response and if I can close the issue.

**Closed** 2022-07-06 18:08 UTC
Labels: question
