### ISSUE TITLE
Auto instrumentation - Metrics not visible in Elastic APM

### ISSUE THREAD

**Issue by oulfik** [open-telemetry/opentelemetry-dotnet-instrumentation#2869] opened 2023-08-23 06:59 UTC
We are currently running a kind cluster on a VM for testing purposes with the following setup:

- Otel collector through an Otel operator
- auto-instrumentation injection with the operator
- Telemetry data is send via auto-instrumented services to the collector and then to Elastic (version 8.8.0)
- Services are implemented in .NET (version 6.0.18)

Traces & logs are visible in Elastic APM but metrics are missing completely as you can see in the screenshot below:

![service_metrics](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/52165945/38b5049b-9014-4973-9e12-3afd77bb8ec3)

Auto instrumentation is enabled by adding the annotation line to the Deployment as described in the documentation:
`instrumentation.opentelemetry.io/inject-dotnet: otel-instrumentation/opentelemetry-instrumentation-test`

I also had to mount two .dll files into the service container for solving a FileNotFoundException. After I used version 7.0 of the .dll files the instrumentation started without an error. 

```
        volumeMounts:
        - mountPath: /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.18/Microsoft.Extensions.Logging.Abstractions.dll
          name: dotnet-logging-package
          subPath: Microsoft.Extensions.Logging.Abstractions.dll
        - mountPath: /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6.0.18/Microsoft.Extensions.Configuration.dll
          name: dotnet-config-package
          subPath: Microsoft.Extensions.Configuration.dll
```

This is our current collector config:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {...}
  creationTimestamp: "2023-07-31T11:20:32Z"
  generation: 14
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
  name: otel-collector-test
  namespace: otel-collector
  resourceVersion: "17483849"
  uid: 381a6f44-58fe-4c33-a9bb-ca7810787ed8
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
	  
    exporters:
      logging:
        verbosity: normal
        sampling_initial: 10
        sampling_thereafter: 5
      elasticsearch:
        endpoints: [https://quickstart-es-http.elastic-test.svc:9200]
        #user: elastic
        api_key: some_api_key
        tls:
          insecure: false
          insecure_skip_verify: true
      otlp/elastic:
        endpoint: "https://apm-apm-sample-apm-http.elastic-test.svc:8200"
        headers:
          Authorization: "some_bearer"
        tls:
          insecure: false
          insecure_skip_verify: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          #processors: [batch] #memory_limiter]
          exporters: [logging, elasticsearch, otlp/elastic]
        metrics:
          receivers: [otlp]
          #processors: [batch] #memory_limiter]
          exporters: [logging, otlp/elastic]
        logs:
          receivers: [otlp]
          #processors: [batch] #memory_limiter]
          exporters: [logging, elasticsearch, otlp/elastic]
  ingress:
    route: {}
  mode: deployment
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  targetAllocator:
    prometheusCR: {}
    resources: {}
  upgradeStrategy: automatic
status:
  image: rb-artifactory.com/otel/opentelemetry-collector-contrib:0.80.0
  scale:
    replicas: 1
    selector: app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=otel-collector.otel-collector-test,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/name=otel-collector-test-collector,app.kubernetes.io/part-of=opentelemetry,app.kubernetes.io/version=latest
    statusReplicas: 1/1
  version: 0.80.0
```
And this is our instrumentation config:

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-apache-httpd-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.3
    instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.7.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-go-image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.1-alpha
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.26.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.40.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.39b0
    kubectl.kubernetes.io/last-applied-configuration: |
	  {...}
  creationTimestamp: "2023-07-31T11:22:28Z"
  generation: 16
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
  name: opentelemetry-instrumentation-test
  namespace: otel-intstrumentation
  resourceVersion: "17488395"
  uid: f28e8044-cf72-462a-a596-99fd9c65554d
spec:
  apacheHttpd:
    configPath: /usr/local/apache2/conf
    image: rb-artifactory.com/otel/autoinstrumentation-apache-httpd:1.0.3
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 128Mi
    version: "2.4"
  dotnet:
    image: rb-artifactory.com/otel/autoinstrumentation-dotnet:0.7.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  exporter:
    endpoint: http://otel-collector-test-collector.otel-collector.svc.cluster.local:4318
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.1-alpha
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
  java:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-test-collector.otel-collector.svc.cluster.local:4317
    image: rb-artifactory.com/otel/autoinstrumentation-java:1.26.0
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
  nginx:
    configFile: /etc/nginx/nginx.conf
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 128Mi
  nodejs:
    image: rb-artifactory.com/otel/autoinstrumentation-nodejs:0.40.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  propagators:
  - tracecontext
  - baggage
  python:
    image: rb-artifactory.com/otel/autoinstrumentation-python:0.39b0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
  resource: {}
  sampler:
    argument: "1"
    type: parentbased_traceidratio
```

Did we miss some configuration for enabling Metrics? Any help would be appreciated.

**Comment by pjanotti** [comment] 2023-08-23 17:08
Hi @oulfik - At first glance config seems correct. What version of the operator are you using?

The logs can be helpful in this case. Could you please share them? They should be under `/var/log/opentelemetry/dotnet`.

**Comment by pjanotti** [comment] 2023-08-23 23:56
Could you also exec `dotnet --info` in the running container?

**Comment by oulfik** [comment] 2023-08-24 08:18
Hello @pjanotti. Here is the dotnet information:

```
global.json file:
  Not found

Host:
  Version:      6.0.18
  Architecture: x64
  Commit:       c76ac56549

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
Here the logs from the otel-dotnet-auto-Notification.Service-21-20230824.log file:

[otel-dotnet-auto-Notification.Service-21-20230824.log](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/12427150/otel-dotnet-auto-Notification.Service-21-20230824.log)


Then from a  otel-dotnet-auto-Notification.Service-21-Loader-20230824.log file:

```
[2023-08-24T07:53:40.4968188Z] [Information] Managed Loader TryLoadManagedAssembly()
```
otel-dotnet-auto-Notification.Service-21-StartupHook-20230824.log file: 

```
[2023-08-24T07:53:36.8464536Z] [Information] Rule Engine: MinSupportedFrameworkRule evaluation success.
[2023-08-24T07:53:38.6248253Z] [Information] Rule Engine: OpenTelemetrySdkMinimumVersionRule evaluation success.
[2023-08-24T07:53:39.1928052Z] [Information] Rule Engine: DiagnosticSourceRule evaluation success.
[2023-08-24T07:53:40.3956267Z] [Information] Initialization.
[2023-08-24T07:53:47.5031253Z] [Information] StartupHook initialized successfully!
```

**Comment by pjanotti** [comment] 2023-08-25 01:16
I have a similar repro for this issue. I will try to debug it.

**Comment by oulfik** [comment] 2023-08-25 16:05
I found this entry in a new logfile that was created recently:

```
[2023-08-25T13:01:45.6979618Z] [Error] EventSource=OpenTelemetry-Exporter-OpenTelemetryProtocol, Message=Exporter failed send data to collector to http://otel-collector-test-collector.otel-collector.svc.cluster.local:4318/v1/metrics endpoint. Data will not be sent. Exception: System.Net.Http.HttpRequestException: Connection refused (otel-collector-test-collector.otel-collector.svc.cluster.local:4318)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.BaseOtlpHttpExportClient`1.SendExportRequest(TRequest request, CancellationToken cancellationToken)
[2023-08-25T13:01:45.6957803Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=Activity started. OperationName = 'MongoDB.Driver.Core.Events.Command', Id = '00-924c7a585f58789c7f3741c4c392e91b-9bf6f18d75b975ce-01'.
[2023-08-25T13:01:45.7003510Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=MetricReader event: 'OpenTelemetry.Exporter.OtlpMetricExporter.Export failed.'
[2023-08-25T13:01:45.7040969Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=MetricReader event: 'ProcessMetrics failed.'
[2023-08-25T13:01:45.7032506Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=Activity stopped. OperationName = 'MongoDB.Driver.Core.Events.Command', Id = '00-924c7a585f58789c7f3741c4c392e91b-9bf6f18d75b975ce-01'.
[2023-08-25T13:01:45.7099429Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=MetricReader event: 'MetricReader.Collect failed.'
[2023-08-25T13:01:45.7124685Z] [Debug] EventSource=OpenTelemetry-Sdk, Message=Activity started. OperationName = 'MongoDB.Driver.Core.Events.Command', Id = '00-2daf7806cfcc1fba74dbfeb6ac8c97c2-1045429df0542d8b-01'.
```

I am not sure if this is the root cause of the problem because this error message also appears for the /traces & /logs endpoint.

**Comment by pjanotti** [comment] 2023-08-25 17:10
As you said: except for the fact that you saw the same for traces this would be a good root cause. 🤔

**Comment by Kielek** [comment] 2023-09-05 05:40
@oulfik, were you able to solve the issue? Based on the logs it looks like a network issue.

**Comment by oulfik** [comment] 2023-09-08 11:08
I am currently on vacation until the 18.09. I will check this again when I'm back.

**Comment by andr3marra** [comment] 2023-09-09 04:53
I started using OpenTelemetry recently. If i'm not mistaken it is not supported in APM UI
"This bridge only supports the tracing API. The Metrics API is currently not supported."
https://www.elastic.co/guide/en/apm/agent/dotnet/current/opentelemetry-bridge.html#otel-metrics

**Comment by oulfik** [comment] 2023-09-20 11:41
Hi @andr3marra 
I think you are right. In the official Elastic APM documentation .NET isn't mentioned in the metrics chapter [here](https://www.elastic.co/guide/en/apm/guide/8.10/data-model-metrics.html).
I also sent the telemetry data from the cartservice (otel-demo) to Elastic and metrics are also not showing up in the Metrics tab.

**Comment by serenachou** [comment] 2023-09-22 14:28
Hello, our Elastic team has confirmed that there is not an out of the box dashboard for OTel metrics yet, but it's on the roadmap at Elastic!  However, the metrics are available in ES, which you can validate via the Discover view in Kibana. We suggest that you take a look at creating a custom Kibana dashboard with those metrics, and feel free to share feedback on what you create to enable us to take that feedback and potentially integrate your thoughts into the released dashboard to come.

**Comment by pellared** [comment] 2023-09-26 06:14
@oulfik I am closing the issue per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2869#issuecomment-1731520231. Please feel create new issues if you encounter any problems.

**Closed by pellared** 2023-09-26 06:14 UTC
